## Here we find if matrix is orthogonal or not

### It requires 3 steps from us 

- 1. Transposing the Matrix

- 2. Inversing the Matrix

- 3. Cheking if Transpose of matrix is equal to inverse of matrix

In [1]:
import numpy as np

Starting from easy one :)

In [2]:
A = np.array([[1, 0, 0],[0, 1, 0],[0, 0, 1]])
A

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [3]:
Atra = np.transpose(A)
Atra

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [4]:
Ainv = np.linalg.inv(A)
Ainv

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
is_orthoganal = np.array_equal(Atra, Ainv)
is_orthoganal

True

Yes indeed it is orthoganal, now lwt's move to bit difficult one

In [6]:
K = np.array([[2/3, 1/3, 2/3], [-2/3, 2/3, 1/3], [1/3, 2/3, -2/3]])
K

array([[ 0.66666667,  0.33333333,  0.66666667],
       [-0.66666667,  0.66666667,  0.33333333],
       [ 0.33333333,  0.66666667, -0.66666667]])

In [7]:
Ktra = np.transpose(K)
Ktra

array([[ 0.66666667, -0.66666667,  0.33333333],
       [ 0.33333333,  0.66666667,  0.66666667],
       [ 0.66666667,  0.33333333, -0.66666667]])

In [8]:
Kinv = np.linalg.inv(K)
Kinv

array([[ 0.66666667, -0.66666667,  0.33333333],
       [ 0.33333333,  0.66666667,  0.66666667],
       [ 0.66666667,  0.33333333, -0.66666667]])

In [9]:
is_orthoganal = np.array_equal(Kinv, Ktra)
is_orthoganal

False

:\ I did not quite understood why it's saying wrong but the arrays are literally same so it should be orthogonal matrix.