There is cool things that can be done with matrix inverse like finding unknowns it's useful when finding 1000 of unkowns instead of using system of equations because it's easier, cheaper, ...

**Python code to find inverse of Matrix**

In [24]:
# [y1] = [x1, x2]* [w1]
# [y2] = [x1, x2]* [w2]

# Here y1 and y2 are outputs like weather, price of home, price of car. 
# x1, x2 are features that make the price like for car : speed, how much fuel does it take? for certain km, max speed ...
# w1, w2 are weights they are such numbers if we know them we can predict what nex time the outcome, because 
# we usually have y and x wieght is a number that mekes relationship between them 



In [25]:
import numpy as np

In [26]:
X = np.array([[2,1],[-5,3]])
X

array([[ 2,  1],
       [-5,  3]])

In [27]:
X_inv = np.linalg.inv(Unknown)
X_inv

array([[ 0.27272727, -0.09090909],
       [ 0.45454545,  0.18181818]])

In [28]:
y = np.array([4, -7])
y

array([ 4, -7])

In [29]:
w = np.dot(X_inv, y)
w

array([1.72727273, 0.54545455])

Here weights are 1.72 & 0.54

### Now let's do something more fun 

#### I found Real estate prices in Tashkent, Uzbekistan which I did not think could find 😎 	

So there is a lot of info but I'm taking just few of them, here is what I'm taking

*I'm only taking district **Chilonzor** so it will be more accure calculation.*
*And I only took with **rooms 2, 3** as less difference as accureate it will be 🙃*





I did not add latitude and longitude because they were very much the same.

In [30]:
# | district  | rooms | size| level| max_levels | price 
# | Chilonzor |   2   | 42  |   4  |     4      | 37000 
# | Chilonzor |   2   | 51  |   2  |     4      | 22200 
# | Chilonzor |   2   | 51  |   2  |     4      | 24200 || we can't take it otherwise it will be singular matrix :/
# | Chilonzor |   2   | 64  |   3  |     4      | 56500 
# | Chilonzor |   2   | 42  |   2  |     4      | 34500 || can't take this too it will not be square 4X5 
# | Chilonzor |   3   | 70  |   5  |     5      | 40000 

From above we can tell something like size matters look 4th one 56500 size 64, but 2nd and third are big at size though cheap so they must be old (size = 51, price = 22200, 24200) other two are nearly same only difference must be location. I think there is no diiference because of building look all of them are max 4 levels so they all should be build within same 20 - 30 years so maybe it's not about oldness huh :/ so hyposethis is wrong **😜** location plays bigger role. and last one really proves that location does matter a lot. Also there is some things we can't add but it also contributes a lot to price which is household appliances.

#### So start sorting out 🙂

In [45]:
# Price  = y
y = np.array([37000, 22200, 40000, 56500])

In [46]:
# Matrix = everything else 
X = np.array([[2, 42, 4, 4], [2, 51, 2, 4], [3, 70, 5, 5], [2, 64, 3, 4]])

# everything is ready start the magic 

#### Our job is to find weights


*1. First find Xinv - x inverse*

In [47]:
import numpy as np
Xinv = np.linalg.inv(X)
Xinv

# so X inverse is ready

array([[-1.50000000e+00,  1.00000000e+00,  2.00000000e+00,
        -2.00000000e+00],
       [-2.85714286e-02, -2.85714286e-02,  3.84307970e-18,
         5.71428571e-02],
       [ 3.71428571e-01, -6.28571429e-01,  8.88178420e-17,
         2.57142857e-01],
       [ 9.28571429e-01,  4.28571429e-01, -1.00000000e+00,
         1.42857143e-01]])

In [49]:
w = np.dot(Xinv, y)
w

array([-66300.        ,   1537.14285714,  14317.14285714,  11942.85714286])

## Here are the magical numbers that we needed. 😄😄

### now If we have X we should be able to predict y 😉 let's check.

#### here is another 4 houses from Chilanzar

I actualy dont expect more than 50% accuracy let's see

In [50]:
# | district  | rooms | size| level| max_levels | price 
# | Chilonzor |   3   | 65  |   1  |     4      | 49500 
# | Chilonzor |   3   | 70  |   3  |     5      | 55000 
# | Chilonzor |   2   | 51  |   2  |     4      | 21200 
# | Chilonzor |   2   | 45  |   2  |     4      | 56500 


In [54]:
# Matrix = everything else 
X = np.array([[3, 65, 1, 4], [3, 70, 3, 5], [2, 51, 2, 4], [2, 45, 2, 4]])
X

array([[ 3, 65,  1,  4],
       [ 3, 70,  3,  5],
       [ 2, 51,  2,  4],
       [ 2, 45,  2,  4]])

In [55]:
w

array([-66300.        ,   1537.14285714,  14317.14285714,  11942.85714286])

#### Theoraticaly X * w = y | in real life ...

In [56]:
np.dot(X, w) # So huh, let's see if  it's actually correct :)

array([-36897.14285714,  11365.71428571,  22200.        ,  12977.14285714])

Not even close

Output should have been something close to :
49500, 55000, 21200, 56500

That's ok I think it's accuray about 20% or less bacuase there was really less data to train if there was like 100 houses it's accuracy might have been between 50 - 90 I think. 

## That is how we predict using Matrix inverse.