### Singular Value Decomposition (SVD)

A = UDV^T

- U is an orthogonal m x m matrix; its columns are the left-singular vectors of A.
- V is an orthogonal n x n matrix; its columns are the right-singular vectors of A.
- D is a diagonal m x n matrix; elements along its diagonal are the singular values of A.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

### Part 1: proving the equation

In [5]:
A = np.array([[-1, 2], [2, 3], [5, 7]])
A

array([[-1,  2],
       [ 2,  3],
       [ 5,  7]])

In [6]:
U, d, VT = np.linalg.svd(A)

In [7]:
U

array([[ 0.11759238, -0.9915756 ,  0.05431254],
       [ 0.38401471, -0.00503269, -0.92331326],
       [ 0.91580824,  0.12943142,  0.38018781]])

In [8]:
VT

array([[ 0.5569756 ,  0.83052885],
       [ 0.83052885, -0.5569756 ]])

In [9]:
d

array([9.3890616, 1.9610003])

In [10]:
np.diag(d)

array([[9.3890616, 0.       ],
       [0.       , 1.9610003]])

D must have same dimensions as A for UDV^T matrix multiplication to be possible:

In [11]:
D = np.concatenate((np.diag(d), [[0, 0]]), axis=0)
D

array([[9.3890616, 0.       ],
       [0.       , 1.9610003],
       [0.       , 0.       ]])

In [12]:
np.dot(U, np.dot(D, VT))

array([[-1.,  2.],
       [ 2.,  3.],
       [ 5.,  7.]])

#### As you can see U*D*V^T is equal to original matrix A   |  great!

#### now let's prove few more things

- Left-singular vectors of A = eigenvectors of AA^T
- Right-singular vectors of A = eigenvectors of A^TA.
- Non-zero singular values of A = square root of eigenvalues of AA^T = square roots of eigenvalues of A^TA

We have so much to prove let's get into work. 😅

### Part 2: Proving Other  Equation

 Look here I'm using square matrix because we can extract eiganval and eiganvec from **square matrix** only

In [14]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In the first formula says that Left-singular vector of A-matrix is equal to A multiplied by it's transpose and if we denote that new matrix by A1 left-singular matrix is equal to A1's eigenvectors, let's see how much is it really true

**U** is our left-singular matrix

In [35]:
U, d, VT = np.linalg.svd(A)

In [36]:
U

array([[-0.21483724,  0.88723069,  0.40824829],
       [-0.52058739,  0.24964395, -0.81649658],
       [-0.82633754, -0.38794278,  0.40824829]])

here we define what A is

In [37]:
A1 = np.dot(A, A.T)
A1

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

find it's Eiganvalue and Eigenvector

In [38]:
Eival1, Eivec1 = np.linalg.eig(A1)

In [39]:
Eivec1

array([[-0.21483724, -0.88723069,  0.40824829],
       [-0.52058739, -0.24964395, -0.81649658],
       [-0.82633754,  0.38794278,  0.40824829]])

In [43]:
U

array([[-0.21483724,  0.88723069,  0.40824829],
       [-0.52058739,  0.24964395, -0.81649658],
       [-0.82633754, -0.38794278,  0.40824829]])

As you can see U **"Left-singular vectors of A"** is same as Eivec1 **"eigenvectors of AA^T"**

### So, we can conclude that the first formula is true.

**VT** is right singular vector of A | VT stands for V transpose

In [44]:
VT

array([[-0.47967118, -0.57236779, -0.66506441],
       [-0.77669099, -0.07568647,  0.62531805],
       [-0.40824829,  0.81649658, -0.40824829]])

In [46]:
A2 = np.dot(A.T, A)
A2

array([[ 66,  78,  90],
       [ 78,  93, 108],
       [ 90, 108, 126]])

In [68]:
Eival2, Eivec2 = np.linalg.eig(A2)

In [69]:
Eivec2

array([[-0.47967118, -0.77669099,  0.40824829],
       [-0.57236779, -0.07568647, -0.81649658],
       [-0.66506441,  0.62531805,  0.40824829]])

In [70]:
VT

array([[-0.47967118, -0.57236779, -0.66506441],
       [-0.77669099, -0.07568647,  0.62531805],
       [-0.40824829,  0.81649658, -0.40824829]])

In [71]:
Eivec2.T

array([[-0.47967118, -0.57236779, -0.66506441],
       [-0.77669099, -0.07568647,  0.62531805],
       [ 0.40824829, -0.81649658,  0.40824829]])

# 😲😲😲 What ?!

### I guess my Laptop is having some problems in calculation because here in the formula Eigvec2 should be equal to VT not Transpose of it 😨.

### Let's prove third formula

So her in third formula it says that Eival1 is equal to Eival2 and equal to square of D

In [72]:
Eival1

array([ 2.83858587e+02,  1.14141342e+00, -4.22289180e-16])

In [73]:
Eival2

array([2.83858587e+02, 1.14141342e+00, 1.03583089e-15])

In [74]:
d ** 2

array([2.83858587e+02, 1.14141342e+00, 1.11205767e-31])

so they are the same except third elements of it which is so close to zero in all of the matrices we can conclude that matrices are equal 

So we proved all three of them Great!